### ISSUE TITLE
When pressing DWN, velocity waits one cycle until speed is actually increased

### ISSUE THREAD

**Issue by white0ut** [hjfreyer/pentris#7]
Another fluidity request. I think it would feel better if immediately after depressing the DWN key, your velocity is increased. If I were to guess how it interacts now, I would say that it feels like once you've pressed DWN, the piece immediately drops one row, waits an entire "normal" cycle, and if the key is still depressed, it will start to progress at the increased downward velocity.

**Comment by hjfreyer** [comment]
Fixed in 4453b8187055097aa0bbd67ba4f051e1382118b9
